/* -----------------------------------------------------------------------------
 *
 *     Copyright (c) 2015  -  GEMALTO DEVELOPMENT - R&D
 *
 * -----------------------------------------------------------------------------
 * GEMALTO MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF
 * THE SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
 * TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE, OR NON-INFRINGEMENT. GEMALTO SHALL NOT BE
 * LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING,
 * MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
 *
 * THIS SOFTWARE IS NOT DESIGNED OR INTENDED FOR USE OR RESALE AS ON-LINE
 * CONTROL EQUIPMENT IN HAZARDOUS ENVIRONMENTS REQUIRING FAIL-SAFE
 * PERFORMANCE, SUCH AS IN THE OPERATION OF NUCLEAR FACILITIES, AIRCRAFT
 * NAVIGATION OR COMMUNICATION SYSTEMS, AIR TRAFFIC CONTROL, DIRECT LIFE
 * SUPPORT MACHINES, OR WEAPONS SYSTEMS, IN WHICH THE FAILURE OF THE
 * SOFTWARE COULD LEAD DIRECTLY TO DEATH, PERSONAL INJURY, OR SEVERE
 * PHYSICAL OR ENVIRONMENTAL DAMAGE ("HIGH RISK ACTIVITIES"). GEMALTO
 * SPECIFICALLY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTY OF FITNESS FOR
 * HIGH RISK ACTIVITIES.
 *
 * -----------------------------------------------------------------------------
 */

#ifndef libmobilesdk_EMErrorDomain_h
#define libmobilesdk_EMErrorDomain_h

/**
 * Domains of Ezio mobile error
 *
 * @since 3.0
 */
#define EZIO_MOBILE_ERROR_DOMAIN_TOKEN                  @"EZIO_MOBILE_ERROR_DOMAIN_TOKEN"
#define EZIO_MOBILE_ERROR_DOMAIN_FINGERPRINT            @"EZIO_MOBILE_ERROR_DOMAIN_FINGERPRINT"
#define EZIO_MOBILE_ERROR_DOMAIN_JAILBREAK_DETECTION    @"EZIO_MOBILE_ERROR_DOMAIN_JAILBREAK_DETECTION"
#define EZIO_MOBILE_ERROR_DOMAIN_OOB                    @"EZIO_MOBILE_ERROR_DOMAIN_OOB"
#define EZIO_MOBILE_ERROR_DOMAIN_PASSWORD               @"EZIO_MOBILE_ERROR_DOMAIN_PASSWORD"
#define EZIO_MOBILE_ERROR_DOMAIN_SECURE_STORAGE         @"EZIO_MOBILE_ERROR_DOMAIN_SECURE_STORAGE"
#define EZIO_MOBILE_ERROR_DOMAIN_UNSPECIFIED            @"EZIO_MOBILE_ERROR_DOMAIN_UNSPECIFIED"

#define EZIO_MOBILE_ERROR_DOMAIN_AUTH_MODE_BIOFP         @"EZIO_MOBILE_ERROR_DOMAIN_AUTH_MODE_BIOFINGERPRINT"

#endif
