/* -----------------------------------------------------------------------------
 *
 *     Copyright (c) 2016  -  GEMALTO DEVELOPMENT - R&D
 *
 * -----------------------------------------------------------------------------
 * GEMALTO MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF
 * THE SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
 * TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE, OR NON-INFRINGEMENT. GEMALTO SHALL NOT BE
 * LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING,
 * MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
 *
 * THIS SOFTWARE IS NOT DESIGNED OR INTENDED FOR USE OR RESALE AS ON-LINE
 * CONTROL EQUIPMENT IN HAZARDOUS ENVIRONMENTS REQUIRING FAIL-SAFE
 * PERFORMANCE, SUCH AS IN THE OPERATION OF NUCLEAR FACILITIES, AIRCRAFT
 * NAVIGATION OR COMMUNICATION SYSTEMS, AIR TRAFFIC CONTROL, DIRECT LIFE
 * SUPPORT MACHINES, OR WEAPONS SYSTEMS, IN WHICH THE FAILURE OF THE
 * SOFTWARE COULD LEAD DIRECTLY TO DEATH, PERSONAL INJURY, OR SEVERE
 * PHYSICAL OR ENVIRONMENTAL DAMAGE ("HIGH RISK ACTIVITIES"). GEMALTO
 * SPECIFICALLY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTY OF FITNESS FOR
 * HIGH RISK ACTIVITIES.
 *
 * -----------------------------------------------------------------------------
 */


#import <Foundation/Foundation.h>
#import "EMSecureString.h"
#import "EMSecureByteArray.h"
#import "EMPinAuthInput.h"
#import "EMTlsConfiguration.h"

/** The supported Provisioning protocols */
typedef NS_ENUM(int, EMMobileProvisioningProtocol)
{
    /** Provisioning protocol version 1 */
    EMMobileProvisioningProtocolVersion1 = 1,
    /** Provisioning protocol version 2 */
    EMMobileProvisioningProtocolVersion2 = 2,
    /** Provisioning protocol version 3 */
    EMMobileProvisioningProtocolVersion3 = 3
};

/**
 * EPS Configuration Builder
 */
@interface EMEpsConfigurationBuilder : NSObject

/**
 The HTTP Headers to be added in the HTTP request.
 */
@property NSDictionary *headers;

/**
 Gets/Sets the transport layer security configuration for the connection. This may be used for test environments where the security of the system is not a concern (e.g. using insecure HTTP connections). See EMTlsConfiguration
 For default instance insecureConnectionAllowed is set to <code>NO</code>
 selfSignedCertAllowed is set to <code>NO</code>
 hostnameMismatchAllowed is set to <code>NO</code>
 */

@property EMTlsConfiguration *tlsConfiguration;
@end

/**
 * Clear Text Secret Token Configuration Builder
 */
@interface EMClearTextSecretTokenConfigurationBuilder : NSObject

/**
 * If wipePinAndSecret is set to <code>YES</code> then the pin  and secret is wipped after use. Default is set to <code>YES</code>
 *
 *  @since 4.0
 */
@property BOOL wipePinAndSecret;

/**
 Returns the User Token Identifier (UTI).
 
 The UTI is an unsigned value ranging from 0x00 to 0xFF (i.e. 0 to 255).
 It is generated by the provisioning server and is part of the credential
 pushed during provisioning. It is guaranteed that two tokens for the
 same end-user (on authentication server) and from the same EPS domain
 will never have the same UTI. See the Enrollment and Provisioning Server
 documentation for domains configuration description.
 
 The UTI is defined only if the token has been created with Provisioning
 Protocol V3.  When the token has been created with Provisioning Protocol
 V1 or V2 the method returns -1.
 
 Default is set to <code>0x01</code>
 
 @since 4.0
 */
@property int userTokenId;

/**
 Gets the token sequence number that distinguishes this token among others
 the users has.
 
 The token sequence number is defined only for CAP tokens and is an
 unsigned value ranging from 0x00 to 0x63 (i.e. 0 to 99). For OATH
 tokens, the method always return 0xFF (i.e. 255).
 
 Default is set to <code>0xFF</code>
 
 @since 4.0
 */
@property int tokenSequenceNumber;

/**
 The provisioning protocol to use when decoding the credentials.

 Default is set to <code>EMProvisioningProtocolVersion3</code>
 
 @since 4.0
 */
@property EMMobileProvisioningProtocol provisioningProtocol;

@end


/**
 * The provisioning configuration
 */
@interface EMProvisioningConfiguration : NSObject

/**
 Wipes internal state of secure container objects.
 */
- (void)wipe;


/**
 * Creates EMProvisioningConfiguration. This instance is used to create a token from a legacy 1.x credential blob.
 * @param codeGeneratorData Code Generation Data blob created by previous Ezio Mobile SDK.
 * @param deviceUniqueData Device Unique Data that the codeGeneratorData is protected under. Provide `nil` if no such data.
 * @param simCardUniqueData SIM Card Unique Data that the codeGeneratorData is protected under. Provide `nil` if no such data.
 * @param provisioningProtocol The provisioning protocol to use when decoding the credentials.
 * @param error If an error occurs, upon return contains an NSError object that describes the problem. error will belong to the `EMLegacyTokenErrorDomain` and contain a `EMLegacyTokenErrorCode`. If you are not interested in possible errors, you may pass in `NULL`.
 * @return EMProvisioningConfiguration instance.
 *
 * @since 4.0
 */
+ (EMProvisioningConfiguration *)legacyTokenConfigurationWithCodeGeneratorData:(id<EMSecureByteArray>)codeGeneratorData
                                                               deviceUniqueData:(id<EMSecureByteArray>)deviceUniqueData
                                                              simCardUniqueData:(id<EMSecureByteArray>)simCardUniqueData
                                                           provisioningProtocol:(EMMobileProvisioningProtocol)provisioningProtocol
                                                                          error:(NSError **)error;

/**
 * Creates EMProvisioningConfiguration. This instance is used for creation of clear text secret token import.
 * @param pin The pin to be used for wrapping the secret. The value stored in this array will be wiped by the constructor if <code>wipePinAndSecret</code> is set to <code>YES</code>.
 * @param secret The clear text secret seed or key to be provisioned in the SDK. The value stored in this array will be wiped by the constructor if in optionalParameters<code>wipePinAndSecret</code> is set to <code>YES</code>.
 * @param optionalParameters Block where optional parameters set. See the EMClearTextSecretTokenConfigurationBuilder class for more details about the parameters and there optiona values.
 * @return EMProvisioningConfiguration instance.
 *
 * @since 4.0
 */
+ (EMProvisioningConfiguration *)clearTextSeedImportConfigurationWithPin:(id<EMPinAuthInput>)pin
                                                                  secret:(id<EMSecureByteArray>)secret
                                                      optionalParameters:(void(^)(EMClearTextSecretTokenConfigurationBuilder *))optionalParameters;

/**
 * Creates offline EMProvisioningConfiguration.
 * @param sessionKey key to decrypt the provisioning response
 * @param hmacKey key to authenticate the provisioning response.
 * @param provisioningResponse the provisioning response from EPS
 * @param provisioningProtocol The provisioning protocol to use when decoding the credentials. 
 * @warning: Must be version 3 or higher.
 * @return EMProvisioningConfiguration instance.
 * @since 4.0
 */
+ (EMProvisioningConfiguration *)offlineTokenConfigurationWithSessionKey:(id<EMSecureByteArray>)sessionKey
                                                             withHmacKey:(id<EMSecureByteArray>)hmacKey
                                                    provisioningResponse:(id<EMSecureByteArray>)provisioningResponse
                                                    provisioningProtocol:(EMMobileProvisioningProtocol)provisioningProtocol;

/**
 * Creates offline EMProvisioningConfiguration.
 * @param sessionKey key to decrypt the provisioning response
 * @param provisioningResponse the provisioning response from EPS
 * @param provisioningProtocol The provisioning protocol to use when decoding the credentials. Must be version 2 or lower.
 * @return EMProvisioningConfiguration instance.
 * @since 4.0
 */
+ (EMProvisioningConfiguration *)offlineTokenConfigurationWithSessionKey:(id<EMSecureByteArray>)sessionKey
                                                    provisioningResponse:(id<EMSecureByteArray>)provisioningResponse
                                                    provisioningProtocol:(EMMobileProvisioningProtocol)provisioningProtocol;

/**
 Creates EMProvisioningConfiguration. This instance to modify Eps configuration.
 @param url The URL of the Enrollment API endpoint, e.g:
 
   - http(s)://&lt;host&gt;:&lt;port&gt;/EnrolmentServlet/GetAppCredentials for EPS 1.x
   - http(s)://&lt;host&gt;:&lt;port&gt;/provisioner/api/provisioning/pp for EPS 2.x
 
 @param rsaKeyId Identifier for the EPS server's public RSA key.
 @param rsaExponent The RSA exponent of the EPS public key (on provisioning protocol level, not transport level).
 @param rsaModulus The RSA modulus of the EPS public key (on provisioning protocol level, not transport level).
 @param registrationCode The registration code.
 @param provisioningProtocol The provisioning protocol to use when decoding the credentials.
 @param optionalParameters Block where optional parameters set. See the EMEpsConfigurationBuilder class for more details about the parameters and there optiona values.
 @return EMProvisioningConfiguration instance.
 
 @since 4.0
 */
+ (EMProvisioningConfiguration *)epsConfigurationWithURL:(NSURL *)url
                                                rsaKeyId:(NSString *)rsaKeyId
                                             rsaExponent:(NSData *)rsaExponent
                                              rsaModulus:(NSData *)rsaModulus
                                        registrationCode:(id <EMSecureString>)registrationCode
                                    provisioningProtocol:(EMMobileProvisioningProtocol)provisioningProtocol
                                      optionalParameters:(void(^)(EMEpsConfigurationBuilder *))optionalParameters;

@end
